/* 42 Brain expanded arcade: small, self-contained games with no dependencies. */
'use strict';
(function () {
  const games = [
    ['grid','Grid Navigator','Click or use arrows to reach the green exit.','strategy'],['balance','Balance Lab','Keep the beam level by placing weights.','strategy'],
    ['code','Code Breaker','Use the clues to enter the three-digit code.','lab'],['circuit','Circuit Builder','Activate nodes in the signal path, in order.','lab'],
    ['tower','Tower Planner','Click floors from foundation to roof.','strategy'],['mirror','Mirror Memory','Reproduce the highlighted cells after they vanish.','memory'],
    ['composer','Sequence Composer','Arrange the tiles into the shown sequence.','memory'],['route','Route Recall','Memorise and recreate the route.','memory'],
    ['sound','Sound Recall','Listen, then repeat the tones in order.','memory'],['rule','Rule Switch','Sort each tile using the rule shown above.','focus'],
    ['target','Target Scan','Find the one target among decoys.','focus'],['filter','Distraction Filter','Click only the blue circles.','focus'],
    ['resource','Resource Manager','Spend 10 units to hit both project goals.','strategy'],['network','Network Builder','Connect every node without crossing lines.','strategy'],
    ['detective','Detective Logic','Infer the only suspect whose clues fit.','lab'],['algorithm','Algorithm Race','Choose the fastest algorithm for the data.','lab'],
    ['trace','Memory Trace','Follow the lit sequence of cells.','memory'],['bug','Bug Hunter','Click every bug, not the helpful stars.','lab'],['maze','Pointer Maze','Guide the cursor through checkpoints in order.','focus']
  ];
  const details = {
    grid:['Logic','2–4 min','Easy'], balance:['Planning','2–3 min','Easy'], code:['Deduction','2–4 min','Medium'],
    circuit:['Sequencing','1–2 min','Easy'], tower:['Planning','1–2 min','Easy'], mirror:['Memory','2–3 min','Medium'],
    composer:['Memory','1–2 min','Easy'], route:['Memory','2–3 min','Medium'], sound:['Memory','2–3 min','Medium'],
    rule:['Focus','1–2 min','Easy'], target:['Focus','1–2 min','Easy'], filter:['Focus','1–2 min','Easy'],
    resource:['Planning','1–2 min','Easy'], network:['Logic','1–2 min','Easy'], detective:['Deduction','1–2 min','Easy'],
    algorithm:['Logic','1–2 min','Easy'], trace:['Memory','2–3 min','Medium'], bug:['Focus','1–2 min','Easy'], maze:['Focus','2–3 min','Medium']
  };
  const byId = Object.fromEntries(games.map(g => [g[0], g]));
  let score = Number(localStorage.getItem('42brain-arcade-score') || 0), current = null;
  const $ = id => document.getElementById(id);
  function cards(container, filter) {
    container.innerHTML = games.filter(g => !filter || g[3] === filter).map(g => { const d=details[g[0]]; return `<button class="arcade-card" data-launch="${g[0]}" aria-label="Play ${g[1]}"><span class="arcade-icon">${icon(g[0])}</span><b>${g[1]}</b><small>${g[2]}</small><span class="game-meta"><em>${d[0]}</em><em>${d[1]}</em><em>${d[2]}</em></span><i>Play game <svg class="ui-icon"><use href="ui-icons.svg#bolt"/></svg></i></button>`; }).join('');
    container.querySelectorAll('[data-launch]').forEach(b => b.onclick = () => launch(b.dataset.launch));
  }
  function icon(id) { const map={grid:'chart',balance:'chart',code:'settings',circuit:'bolt',tower:'chart',mirror:'brain',composer:'book',route:'target',sound:'timer',rule:'target',target:'target',filter:'target',resource:'chart',network:'users',detective:'lightbulb',algorithm:'bolt',trace:'brain',bug:'target',maze:'target'}; return `<svg class="ui-icon"><use href="ui-icons.svg#${map[id]||'brain'}"/></svg>`; }
  function nav(page) {
    document.querySelectorAll('[data-workspace-page]').forEach(p => p.classList.toggle('active', p.dataset.workspacePage === page));
    document.querySelectorAll('.workspace-nav [data-page]').forEach(b => b.classList.toggle('active', b.dataset.page === page));
    const active=document.querySelector(`.workspace-nav [data-page="${page}"] span`);
    const crumb=$('workspaceBreadcrumb');
    if(crumb&&active) crumb.querySelector('strong').textContent=active.textContent;
    if (page === 'progress') renderProgress();
  }
  function launch(id) {
    current = id; let modal = $('arcadeModal');
    if (!modal) { modal = document.createElement('div'); modal.id = 'arcadeModal'; modal.className = 'arcade-modal'; document.body.appendChild(modal); }
    modal.innerHTML = `<div class="arcade-dialog" role="dialog" aria-modal="true" aria-labelledby="arcadeTitle"><header><div><span class="eyebrow">Arcade / ${byId[id][3]}</span><h2 id="arcadeTitle">${byId[id][1]}</h2></div><button class="icon-btn" id="closeArcade" aria-label="Close game"><svg class="ui-icon"><use href="ui-icons.svg#target"/></svg></button></header><p class="game-help">${byId[id][2]}</p><div class="game-status"><span>Objective: complete the board</span><span>Best: ${Number(localStorage.getItem('42brain-best-'+id)||0)} pts</span></div><div id="gameBoard"></div><div id="gameMessage" class="game-message" role="status" aria-live="polite"></div><div class="game-actions"><button class="sec-btn" id="resetArcade">Reset</button><button class="cta-btn" id="newArcade">New game</button></div></div>`;
    modal.classList.add('open'); $('closeArcade').onclick = () => modal.classList.remove('open'); $('resetArcade').onclick = () => renderGame(id); $('newArcade').onclick = () => renderGame(id); modal.onkeydown=e=>{if(e.key==='Escape')modal.classList.remove('open')}; renderGame(id); $('closeArcade').focus();
  }
  function board(html) { $('gameBoard').innerHTML = html; $('gameMessage').textContent = ''; $('gameMessage').dataset.done=''; }
  function done(ok, text) { if ($('gameMessage').dataset.done) return; $('gameMessage').textContent = text || (ok ? 'Great work! +10 points' : 'Not quite — reset and try again.'); $('gameMessage').dataset.done='1'; if (ok) { score += 10; localStorage.setItem('42brain-arcade-score', score); localStorage.setItem('42brain-best-'+current, Math.max(10,Number(localStorage.getItem('42brain-best-'+current)||0))); } }
  function shuffled(a) { return a.sort(() => Math.random() - .5); }
  function renderGame(id) {
    const b = $('gameBoard');
    if (id === 'grid' || id === 'maze') {
      const n = id === 'grid' ? 5 : 4, goal = n*n-1; let pos=0, checks=id==='maze'?[0,1,5,9,10,14,15]:[0];
      b.innerHTML=`<div class="play-grid ${id}" style="--size:${n}">${Array.from({length:n*n},(_,i)=>`<button data-i="${i}" class="${i===goal?'goal':''}">${i===goal?'EXIT':''}</button>`).join('')}</div><small>Arrow keys or click an adjacent cell. ${id==='maze'?'Touch each checkpoint in order.':''}</small>`;
      const move = i => { if (Math.abs(i-pos)!==1 && Math.abs(i-pos)!==n) return; pos=i; b.querySelectorAll('button').forEach(x=>x.classList.remove('player')); b.querySelector(`[data-i="${i}"]`).classList.add('player'); if (id==='grid'&&i===goal) done(true,'Exit reached!'); if(id==='maze'&&i===checks[0]){checks.shift(); if(!checks.length)done(true,'Maze mastered!');} };
      b.querySelectorAll('button').forEach(x=>x.onclick=()=>move(+x.dataset.i)); b.onkeydown=e=>{let i=pos;if(e.key==='ArrowRight')i++;if(e.key==='ArrowLeft')i--;if(e.key==='ArrowDown')i+=n;if(e.key==='ArrowUp')i-=n;if(i>=0&&i<n*n)move(i)}; b.tabIndex=0;b.focus(); return;
    }
    if(id==='balance'){let left=0,right=0; board('<div class="balance-beam"><span id="beam"><svg class="ui-icon"><use href="ui-icons.svg#chart"/></svg></span></div><div class="weight-row">'+[1,2,3,4].map(x=>`<button data-w="${x}">Weight ${x}</button>`).join('')+'</div>'); b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(Math.random()>.5)left+=+x.dataset.w;else right+=+x.dataset.w; $('beam').style.transform=`rotate(${Math.max(-25,Math.min(25,(right-left)*4))}deg)`; if(left+right>=10)done(left===right,'Beam '+(left===right?'level!':'tilted — reset and try again.'))}); return;}
    if(id==='code'){let secret=String([0,2,4,6,8][Math.floor(Math.random()*5)]); while(secret.length<3){let d=Math.floor(Math.random()*10);if(!secret.includes(String(d)))secret+=d} board(`<div class="code-clues">3 unique digits. First digit is even; digits sum to ${[...secret].reduce((a,x)=>a+ +x,0)}.</div><input id="codeInput" class="code-input" inputmode="numeric" maxlength="3" placeholder="Enter code" aria-label="Three digit code"><button id="codeSubmit" class="cta-btn">Unlock</button>`); $('codeSubmit').onclick=()=>done($('codeInput').value===secret,'The lock '+($('codeInput').value===secret?'opens!':'stays closed. The code was '+secret+'.')); return;}
    if(id==='circuit'){let order=shuffled([1,2,3,4]),next=1; board(`<div class="node-row">${order.map(x=>`<button class="node" data-n="${x}">NODE ${x}</button>`).join('')}</div>`); b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(+x.dataset.n===next){x.classList.add('on');next++;if(next===5)done(true,'Circuit powered!')}else done(false,'Signal lost — start a new circuit.');});return;}
    if(id==='tower'){let order=shuffled(['Foundation','Frame','Roof','Antenna']);board('<div class="tower-stack">'+order.map(x=>`<button data-v="${x}">${x}</button>`).join('')+'</div><small>Foundation → Frame → Roof → Antenna</small>');let n=0; b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(x.dataset.v===['Foundation','Frame','Roof','Antenna'][n]){x.disabled=true;n++;if(n===4)done(true,'Tower complete!')}else done(false,'That floor cannot be placed yet.');});return;}
    if(id==='mirror'||id==='route'||id==='trace'){let n=4, seq=shuffled([...Array(n*n).keys()]).slice(0,id==='trace'?5:4);if(id==='route')seq=[0,1,2,6];let shown=true; board(`<div class="play-grid memory-grid" style="--size:${n}">${Array.from({length:n*n},(_,i)=>`<button data-i="${i}" class="${seq.includes(i)?'lit':''}"></button>`).join('')}</div><button id="hideMemory" class="sec-btn">Hide pattern</button>`); $('hideMemory').onclick=()=>{shown=false;b.querySelectorAll('.lit').forEach(x=>x.classList.remove('lit'));let got=[];b.querySelectorAll('[data-i]').forEach(x=>x.onclick=()=>{if(shown)return;let i=+x.dataset.i;if(id==='route'&&got.length&&Math.abs(i-got[got.length-1])!==1&&Math.abs(i-got[got.length-1])!==n)return;if(id==='trace'&&i!==seq[got.length])return; x.classList.add('picked');got.push(i);if(got.length===seq.length)done(id==='trace'?got.every((x,j)=>x===seq[j]):id==='route'?got.every((x,j)=>x===seq[j]):seq.every(x=>got.includes(x)),id==='route'?'Route recreated!':'Pattern recalled!');});};return;}
    if(id==='composer'){let answer=['A','B','C','D'], tiles=shuffled(answer.slice());board('<div class="tile-row">'+tiles.map(x=>`<button data-v="${x}">${x}</button>`).join('')+'</div><small>Click in alphabetical order.</small>');let n=0;b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(x.dataset.v===answer[n]){x.disabled=true;n++;if(n===4)done(true,'Sequence composed!')}else done(false,'That tile is out of order.');});return;}
    if(id==='sound'){let seq=shuffled([0,1,2,3]).slice(0,3), got=[];board('<button id="playTones" class="cta-btn">▶ Play tones</button><div class="tone-row">'+[0,1,2,3].map(x=>`<button data-tone="${x}">${x+1}</button>`).join('')+'</div>');$('playTones').onclick=()=>{seq.forEach((x,i)=>setTimeout(()=>tone(220+x*100),i*350));};b.querySelectorAll('[data-tone]').forEach(x=>x.onclick=()=>{got.push(+x.dataset.tone);if(got.length===seq.length)done(got.every((x,i)=>x===seq[i]),'Tone sequence '+(got.every((x,i)=>x===seq[i])?'matched!':'missed.'));});return;}
    if(id==='rule'||id==='filter'){let rule=id==='rule', vals=shuffled(rule?['▲','●','▲','●','▲','●']:['blue','red','blue','yellow','blue','red']);board(`<p class="rule-banner">${rule?'Click triangles only':'Click blue only'}</p><div class="shape-row">${vals.map((v,i)=>`<button class="${v}" data-good="${rule?v==='▲':v==='blue'}">${v}</button>`).join('')}</div>`);b.querySelectorAll('button:not(.rule-banner)').forEach(x=>x.onclick=()=>{if(x.dataset.good==='true'){x.disabled=true;if(!b.querySelector('[data-good="true"]:not(:disabled)'))done(true,'Signal filtered!')}else done(false,'Distraction clicked.');});return;}
    if(id==='target'){board('<div class="target-field">'+Array.from({length:24},(_,i)=>`<button class="${i===17?'true-target':''}">•</button>`).join('')+'</div>');b.querySelectorAll('button').forEach(x=>x.onclick=()=>done(x.classList.contains('true-target'),x.classList.contains('true-target')?'Target acquired!':'Decoy.'));return;}
    if(id==='resource'){board('<p>Allocate 10 units: production needs 6+, quality needs 3+.</p><input id="prod" type="range" min="0" max="10" value="5"><output id="alloc">Production 5 · Quality 5</output><button id="allocDone" class="cta-btn">Commit plan</button>');$('prod').oninput=e=>{$('alloc').textContent=`Production ${e.target.value} · Quality ${10-e.target.value}`};$('allocDone').onclick=()=>done(+$('prod').value>=6&&10-+$('prod').value>=3,'Plan '+(+$('prod').value>=6&&10-+$('prod').value>=3?'approved!':'fails a requirement.'));return;}
    if(id==='network'){board('<div class="network-nodes">'+[0,1,2,3].map(x=>`<button data-n="${x}">${x+1}</button>`).join('')+'</div><small>Connect 1 → 2 → 3 → 4.</small>');let n=0; b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(+x.dataset.n===n){x.classList.add('on');n++;if(n===4)done(true,'Network connected!')}else done(false,'That node is unreachable next.');});return;}
    if(id==='detective'){board('<p>Exactly one suspect has all three clues: wears red, was seen at 9, owns a key.</p><div class="suspects">'+['Ava · red · 9 · key','Bo · blue · 9 · key','Cy · red · 8 · key'].map((x,i)=>`<button data-i="${i}">${x}</button>`).join('')+'</div>');b.querySelectorAll('button').forEach(x=>x.onclick=()=>done(x.dataset.i==='0','Case '+(x.dataset.i==='0'?'solved!':'still open.')));return;}
    if(id==='algorithm'){board('<p>For 1,000 sorted records, which is fastest?</p>'+['Linear search · O(n)','Binary search · O(log n)','Bubble sort · O(n²)'].map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join(''));b.querySelectorAll('button').forEach(x=>x.onclick=()=>done(x.dataset.i==='1','Benchmark '+(x.dataset.i==='1'?'won!':'lost.')));return;}
    if(id==='bug'){board('<div class="bug-field">'+Array.from({length:20},(_,i)=>`<button class="${i%7===0?'bug':''}">${i%7===0?'🐛':'★'}</button>`).join('')+'</div>');let bugs=b.querySelectorAll('.bug').length;b.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(x.classList.contains('bug')){x.disabled=true;if(!--bugs)done(true,'All bugs squashed!')}else done(false,'That was a helpful star.');});}
  }
  function tone(freq){try{const C=window.AudioContext||window.webkitAudioContext, c=new C(),o=c.createOscillator();o.frequency.value=freq;o.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch(e){}}
  function renderProgress(){const p=$('workspaceProgress');if(p)p.innerHTML=`<div class="progress-big">${score}</div><p>Arcade points earned on this device.</p><div class="progress-bar"><i style="width:${Math.min(100,score/2)}%"></i></div>`;const s=$('workspaceScore');if(s)s.textContent=score;}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.game-catalog').forEach(c=>cards(c,c.dataset.filter));const all=$('gameCatalog');if(all)cards(all);document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>nav(x.dataset.page));$('workspaceLaunch').onclick=()=>{document.getElementById('splash').classList.remove('active');document.getElementById('workspace').classList.add('active');nav('home');};$('workspaceBack').onclick=()=>{document.getElementById('workspace').classList.remove('active');document.getElementById('splash').classList.add('active')};$('workspaceClassic').onclick=()=>{$('workspace').classList.remove('active');$('splash').classList.add('active');};$('workspaceTheme').onchange=e=>{document.body.classList.toggle('dark',e.target.value==='dark');};$('workspaceReset').onclick=()=>{score=0;localStorage.removeItem('42brain-arcade-score');renderProgress()};$('arcadeHelp').onclick=()=>$('arcadeHelpPanel').classList.toggle('hidden');renderProgress();const original=document.getElementById('splash');document.querySelectorAll('#statsNavBtn,#planBtn').forEach(x=>x.addEventListener('contextmenu',e=>e.preventDefault()));document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>{if(x.dataset.page){original.classList.remove('active');document.getElementById('workspace').classList.add('active')}}));});
})();
