/* 42 Brain Arcade catalogue. */
'use strict';

window.ArcadeCatalog = [
  { id: 'grid', title: 'Grid Navigator', lane: 'strategy', icon: 'chart',
    objective: 'Reach the EXIT by moving one square at a time without leaving the grid.', controls: 'Click an adjacent square or use the arrow keys.', level: 'Starter', time: '2 min' },
  { id: 'balance', title: 'Balance Lab', lane: 'strategy', icon: 'chart',
    objective: 'Place every weight so the two sides of the beam have the same total.', controls: 'Choose a side for each weight, then submit the balance.', level: 'Starter', time: '2 min' },
  { id: 'tower', title: 'Tower Planner', lane: 'strategy', icon: 'chart',
    objective: 'Build a tower from Foundation to Antenna in the correct order.', controls: 'Select the next floor. A wrong floor ends the attempt.', level: 'Starter', time: '1 min' },
  { id: 'resource', title: 'Resource Manager', lane: 'strategy', icon: 'chart',
    objective: 'Allocate exactly 10 units while giving production 6+ and quality 3+.', controls: 'Set the slider, then commit the plan.', level: 'Starter', time: '1 min' },
  { id: 'network', title: 'Network Builder', lane: 'strategy', icon: 'users',
    objective: 'Connect every node by selecting 1 → 2 → 3 → 4.', controls: 'Select the next node. An incorrect link fails the run.', level: 'Starter', time: '1 min' },
  { id: 'routeplan', title: 'Route Planner', lane: 'strategy', icon: 'target',
    objective: 'Find the shortest safe route through a changing grid.', controls: 'Choose adjacent cells while avoiding blocked squares.', level: 'Focused', time: '2 min' },
  { id: 'priority', title: 'Priority Queue', lane: 'strategy', icon: 'chart',
    objective: 'Sort tasks by urgency, impact and deadline.', controls: 'Select the task that should be handled next.', level: 'Focused', time: '2 min' },
  { id: 'schedule', title: 'Schedule Builder', lane: 'strategy', icon: 'calendar',
    objective: 'Fit tasks into the available time without breaking dependencies.', controls: 'Place each task in the only valid slot.', level: 'Focused', time: '2 min' },
  { id: 'risk', title: 'Risk & Reward', lane: 'strategy', icon: 'bolt',
    objective: 'Choose a sequence of moves that maximises reward without exceeding the risk budget.', controls: 'Pick one action per round.', level: 'Focused', time: '2 min' },
  { id: 'mirror', title: 'Mirror Memory', lane: 'memory', icon: 'brain',
    objective: 'Memorise the highlighted cells and reproduce the complete pattern.', controls: 'Press Hide pattern, then select every highlighted cell.', level: 'Focused', time: '2 min' },
  { id: 'composer', title: 'Sequence Composer', lane: 'memory', icon: 'book',
    objective: 'Arrange the four tiles into the requested A → B → C → D sequence.', controls: 'Select tiles in order. A wrong tile fails the attempt.', level: 'Starter', time: '1 min' },
  { id: 'route', title: 'Route Recall', lane: 'memory', icon: 'target',
    objective: 'Memorise the highlighted route and recreate each connected step.', controls: 'Hide the route, then click the cells in order.', level: 'Focused', time: '2 min' },
  { id: 'sound', title: 'Sound Recall', lane: 'memory', icon: 'timer',
    objective: 'Listen to the tone sequence and repeat it without an error.', controls: 'Press Play, then use 1–4 or click the tone buttons.', level: 'Focused', time: '2 min' },
  { id: 'trace', title: 'Memory Trace', lane: 'memory', icon: 'brain',
    objective: 'Watch the cells light up, then repeat the exact sequence.', controls: 'Press Hide sequence, then click the cells in order.', level: 'Focused', time: '2 min' },
  { id: 'numberrecall', title: 'Number Recall', lane: 'memory', icon: 'book',
    objective: 'Hold a growing number sequence in working memory and reproduce it.', controls: 'Memorise the digits, hide them, then type the sequence.', level: 'Starter', time: '2 min' },
  { id: 'cardmemory', title: 'Card Memory', lane: 'memory', icon: 'brain',
    objective: 'Remember where matching symbols are hidden on the board.', controls: 'Reveal pairs by selecting two cards at a time.', level: 'Focused', time: '2 min' },
  { id: 'delayed', title: 'Delayed Recall', lane: 'memory', icon: 'timer',
    objective: 'Remember a target shown earlier while solving an unrelated task.', controls: 'Answer the final recall prompt after the delay.', level: 'Focused', time: '2 min' },
  { id: 'dual', title: 'Dual Memory', lane: 'memory', icon: 'users',
    objective: 'Remember both symbols and positions at the same time.', controls: 'Reproduce the requested symbol at its remembered position.', level: 'Expert', time: '2 min' },
  { id: 'rule', title: 'Rule Switch', lane: 'focus', icon: 'target',
    objective: 'Select every triangle and ignore every circle.', controls: 'Click all matching shapes. A distractor ends the run.', level: 'Starter', time: '1 min' },
  { id: 'target', title: 'Target Scan', lane: 'focus', icon: 'target',
    objective: 'Find the single solid diamond hidden among outline decoys.', controls: 'Click the target once. A decoy is a miss.', level: 'Starter', time: '1 min' },
  { id: 'filter', title: 'Distraction Filter', lane: 'focus', icon: 'target',
    objective: 'Select every blue circle while ignoring red and yellow circles.', controls: 'Click all blue circles. A wrong colour ends the run.', level: 'Starter', time: '1 min' },
  { id: 'gonogo', title: 'Go / No-Go', lane: 'focus', icon: 'target',
    objective: 'Respond to targets and inhibit responses to distractors.', controls: 'Click only when the target appears.', level: 'Focused', time: '1 min' },
  { id: 'changes', title: 'Change Detection', lane: 'focus', icon: 'brain',
    objective: 'Spot the single object that changed between two displays.', controls: 'Study the first grid, then identify the changed cell.', level: 'Focused', time: '2 min' },
  { id: 'peripheral', title: 'Peripheral Sweep', lane: 'focus', icon: 'target',
    objective: 'Keep the center in view and detect the brief signal at the edge.', controls: 'Choose the side where the signal appeared.', level: 'Focused', time: '1 min' },
  { id: 'moving', title: 'Moving Target', lane: 'focus', icon: 'target',
    objective: 'Track one moving target while similar decoys cross its path.', controls: 'Follow the target and select it when the field freezes.', level: 'Focused', time: '2 min' },
  { id: 'reaction', title: 'Reaction Lab', lane: 'speed', icon: 'timer',
    objective: 'React as quickly as possible when the signal changes.', controls: 'Wait for GO, then press the button once.', level: 'Starter', time: '1 min' },
  { id: 'quickmath', title: 'Quick Math', lane: 'math', icon: 'chart',
    objective: 'Solve short arithmetic problems before the clock closes.', controls: 'Choose the correct answer.', level: 'Starter', time: '1 min' },
  { id: 'compare', title: 'Rapid Compare', lane: 'speed', icon: 'bolt',
    objective: 'Determine which value is larger with minimal hesitation.', controls: 'Choose left or right.', level: 'Starter', time: '1 min' },
  { id: 'visualsearch', title: 'Visual Search', lane: 'speed', icon: 'target',
    objective: 'Find the only matching symbol in a dense field.', controls: 'Tap the exact match.', level: 'Focused', time: '1 min' },
  { id: 'code', title: 'Code Breaker', lane: 'technical', icon: 'settings',
    objective: 'Use the clues to enter the unique three-digit access code.', controls: 'Type three digits and press Enter or Unlock.', level: 'Focused', time: '2 min' },
  { id: 'circuit', title: 'Circuit Builder', lane: 'technical', icon: 'bolt',
    objective: 'Power the circuit by activating nodes 1 through 4 in order.', controls: 'Select the next numbered node. An incorrect node fails the run.', level: 'Starter', time: '1 min' },
  { id: 'algorithm', title: 'Algorithm Race', lane: 'technical', icon: 'bolt',
    objective: 'Choose the most efficient search for 1,000 sorted records.', controls: 'Select the answer that has the lowest complexity.', level: 'Starter', time: '1 min' },
  { id: 'binary', title: 'Binary Logic', lane: 'technical', icon: 'settings',
    objective: 'Convert a short binary expression into the correct decimal value.', controls: 'Choose the correct result.', level: 'Focused', time: '1 min' },
  { id: 'sort', title: 'Sort Lab', lane: 'technical', icon: 'settings',
    objective: 'Identify the fastest sorting strategy for the current data shape.', controls: 'Choose the best algorithm.', level: 'Focused', time: '1 min' },
  { id: 'output', title: 'Output Predictor', lane: 'technical', icon: 'book',
    objective: 'Predict the output of a tiny algorithm before it runs.', controls: 'Choose the exact final output.', level: 'Focused', time: '2 min' },
  { id: 'bug', title: 'Bug Hunter', lane: 'technical', icon: 'target',
    objective: 'Squash every bug without clicking a helpful star.', controls: 'Click each bug. A star is a false positive.', level: 'Starter', time: '1 min' },
  { id: 'pointer', title: 'Pointer Maze', lane: 'technical', icon: 'target',
    objective: 'Move through each green checkpoint in order to reach the finish.', controls: 'Click an adjacent cell or use arrow keys.', level: 'Focused', time: '2 min' },
  { id: 'graph', title: 'Graph Traversal', lane: 'technical', icon: 'users',
    objective: 'Visit every required node using the fewest edges.', controls: 'Choose the next connected node.', level: 'Expert', time: '2 min' },
  { id: 'stack', title: 'Stack & Queue', lane: 'technical', icon: 'chart',
    objective: 'Apply push, pop, enqueue and dequeue operations correctly.', controls: 'Choose the next item that leaves the structure.', level: 'Focused', time: '2 min' },
  { id: 'recursion', title: 'Recursion Trace', lane: 'technical', icon: 'brain',
    objective: 'Follow recursive calls and identify the final returned value.', controls: 'Choose the correct result.', level: 'Expert', time: '2 min' },
  { id: 'matrix', title: 'Matrix Logic', lane: 'lab', icon: 'lightbulb',
    objective: 'Infer the missing cell from a 3×3 transformation matrix.', controls: 'Choose the cell that completes the rule.', level: 'Focused', time: '2 min' },
  { id: 'truth', title: 'Truth Table', lane: 'lab', icon: 'lightbulb',
    objective: 'Determine which statement can be true under the given conditions.', controls: 'Choose the only consistent statement.', level: 'Focused', time: '2 min' },
  { id: 'deduction', title: 'Deduction Grid', lane: 'lab', icon: 'book',
    objective: 'Use a compact set of clues to identify the only valid arrangement.', controls: 'Select the arrangement that satisfies every clue.', level: 'Focused', time: '2 min' },
  { id: 'conditional', title: 'Conditional Logic', lane: 'lab', icon: 'settings',
    objective: 'Apply IF/THEN rules to determine the final state.', controls: 'Choose the resulting state.', level: 'Focused', time: '1 min' },
  { id: 'operator', title: 'Missing Operator', lane: 'lab', icon: 'chart',
    objective: 'Fill the missing operator so the equation is correct.', controls: 'Choose +, −, × or ÷.', level: 'Starter', time: '1 min' },
  { id: 'debug', title: 'Debug the Algorithm', lane: 'lab', icon: 'settings',
    objective: 'Find the single incorrect step in a short algorithm trace.', controls: 'Select the faulty line.', level: 'Focused', time: '2 min' },
  { id: 'detective', title: 'Detective Logic', lane: 'lab', icon: 'lightbulb',
    objective: 'Identify the only suspect who matches all three clues.', controls: 'Read the evidence, then select one suspect.', level: 'Starter', time: '1 min' }
];
