/* 42 Brain Arcade catalogue. No build step: this file exposes a small global
   consumed by arcade.js and games.js so the app can still be opened from disk. */
'use strict';

window.ArcadeCatalog = [
  { id: 'grid', title: 'Grid Navigator', lane: 'strategy', icon: 'chart',
    objective: 'Reach the EXIT by moving one square at a time without leaving the grid.',
    controls: 'Click an adjacent square or use the arrow keys.', level: 'Starter', time: '2 min' },
  { id: 'balance', title: 'Balance Lab', lane: 'strategy', icon: 'chart',
    objective: 'Place every weight so the two sides of the beam have the same total.',
    controls: 'Choose a side for each weight, then submit the balance.', level: 'Starter', time: '2 min' },
  { id: 'code', title: 'Code Breaker', lane: 'lab', icon: 'settings',
    objective: 'Use the clues to enter the unique three-digit access code.',
    controls: 'Type three digits and press Enter or Unlock.', level: 'Focused', time: '2 min' },
  { id: 'circuit', title: 'Circuit Builder', lane: 'lab', icon: 'bolt',
    objective: 'Power the circuit by activating nodes 1 through 4 in order.',
    controls: 'Select the next numbered node. An incorrect node fails the run.', level: 'Starter', time: '1 min' },
  { id: 'tower', title: 'Tower Planner', lane: 'strategy', icon: 'chart',
    objective: 'Build a tower from Foundation to Antenna in the correct order.',
    controls: 'Select the next floor. A wrong floor ends the attempt.', level: 'Starter', time: '1 min' },
  { id: 'mirror', title: 'Mirror Memory', lane: 'memory', icon: 'brain',
    objective: 'Memorise the highlighted cells and reproduce the complete pattern.',
    controls: 'Press Hide pattern, then select every highlighted cell.', level: 'Focused', time: '2 min' },
  { id: 'composer', title: 'Sequence Composer', lane: 'memory', icon: 'book',
    objective: 'Arrange the four tiles into the requested A → B → C → D sequence.',
    controls: 'Select tiles in order. A wrong tile fails the attempt.', level: 'Starter', time: '1 min' },
  { id: 'route', title: 'Route Recall', lane: 'memory', icon: 'target',
    objective: 'Memorise the highlighted route and recreate each connected step.',
    controls: 'Hide the route, then click the cells in order.', level: 'Focused', time: '2 min' },
  { id: 'sound', title: 'Sound Recall', lane: 'memory', icon: 'timer',
    objective: 'Listen to the tone sequence and repeat it without an error.',
    controls: 'Press Play, then use 1–4 or click the tone buttons.', level: 'Focused', time: '2 min' },
  { id: 'rule', title: 'Rule Switch', lane: 'focus', icon: 'target',
    objective: 'Select every triangle and ignore every circle.',
    controls: 'Click all matching shapes. A distractor ends the run.', level: 'Starter', time: '1 min' },
  { id: 'target', title: 'Target Scan', lane: 'focus', icon: 'target',
    objective: 'Find the single solid diamond hidden among outline decoys.',
    controls: 'Click the target once. A decoy is a miss.', level: 'Starter', time: '1 min' },
  { id: 'filter', title: 'Distraction Filter', lane: 'focus', icon: 'target',
    objective: 'Select every blue circle while ignoring red and yellow circles.',
    controls: 'Click all blue circles. A wrong colour ends the run.', level: 'Starter', time: '1 min' },
  { id: 'resource', title: 'Resource Manager', lane: 'strategy', icon: 'chart',
    objective: 'Allocate exactly 10 units while giving production 6+ and quality 3+.',
    controls: 'Set the slider, then commit the plan.', level: 'Starter', time: '1 min' },
  { id: 'network', title: 'Network Builder', lane: 'strategy', icon: 'users',
    objective: 'Connect every node by selecting 1 → 2 → 3 → 4.',
    controls: 'Select the next node. An incorrect link fails the run.', level: 'Starter', time: '1 min' },
  { id: 'detective', title: 'Detective Logic', lane: 'lab', icon: 'lightbulb',
    objective: 'Identify the only suspect who matches all three clues.',
    controls: 'Read the evidence, then select one suspect.', level: 'Starter', time: '1 min' },
  { id: 'algorithm', title: 'Algorithm Race', lane: 'lab', icon: 'bolt',
    objective: 'Choose the most efficient search for 1,000 sorted records.',
    controls: 'Select the answer that has the lowest complexity.', level: 'Starter', time: '1 min' },
  { id: 'trace', title: 'Memory Trace', lane: 'memory', icon: 'brain',
    objective: 'Watch the cells light up, then repeat the exact sequence.',
    controls: 'Press Hide sequence, then click the cells in order.', level: 'Focused', time: '2 min' },
  { id: 'bug', title: 'Bug Hunter', lane: 'lab', icon: 'target',
    objective: 'Squash every bug without clicking a helpful star.',
    controls: 'Click each bug. A star is a false positive.', level: 'Starter', time: '1 min' },
  { id: 'maze', title: 'Pointer Maze', lane: 'focus', icon: 'target',
    objective: 'Move through each green checkpoint in order to reach the finish.',
    controls: 'Click an adjacent cell or use arrow keys.', level: 'Focused', time: '2 min' }
];
